export * from "./Home-section/Home-section/0-Home-section-provider";
export * from "./Home-section/Our-Treatment-section/1-our-Treatment-section/0-our-Treatment-section-provider";
export * from "./Home-section/Works-section/1-works-section/0-works-section-provider";
export * from "./Home-section/Package-section/1-package-section/0-pakage-section-provider";
export * from "./Home-section/Call-Section/1-call-section/0-call-section-Catalog-provider";
export * from "./Home-section/Our-makeup-section/1-our-makeup-section/0-ourMackeup-section-Catalog-provider";
export * from "./Home-section/Counter-section/1-Counter-section/0-Counter-section-Catalog-provider";
export * from "./Home-section/Gallery-section/1-Gallery-section/0-Gallery-section-Catalog-provider";
export * from "./Home-section/News-section/1-News-section/0-News-section-Catalog-provider";
